version: '3.3'

services:
    db:
        image: postgres
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        networks:
          - djangonetwork
    web:
        build: .
        command: bash -c "
          python finance_api/manage.py migrate &&
          python finance_api/manage.py api_parsing &&
          python finance_api/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/test_task_data_ox
        ports:
            - 8000:8000
        depends_on:
          - db
        links:
          - db:db
        networks:
          - djangonetwork

networks:
    djangonetwork:
        driver: bridge

volumes:
  postgres_data: