version: '3.8'

services:
    db:
        image: postgres
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
    web:
        build: .
        command: python manage.py api_parsing
        volumes:
            - .:/yahoo_data_api
        ports:
            - "8000:8000"
        depends_on:
            - db